### ISSUE TITLE
Unable to run Amigo on Android 4.0.4

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#1]
Firstly I tried to search it on Play Market. No success (scrolled at least 200 apps)
![screenshot_2015-09-07-16-21-44](https://cloud.githubusercontent.com/assets/592627/9717739/cfa8a820-557d-11e5-93d0-3d48d144468e.jpg)

Later I went directly to app URL and still after that no success
![screenshot_2015-09-07-16-13-59](https://cloud.githubusercontent.com/assets/592627/9717738/cfa87044-557d-11e5-97e2-9ea8696783a8.jpg)

After occasionally searched again and app appeared in search. Installed it. Got a message that this app is compatible with some of my devices. Don't know what exactly it means but can't open an app and it is not in my app list.
![screenshot_2015-09-07-16-15-31](https://cloud.githubusercontent.com/assets/592627/9717737/cfa68d9c-557d-11e5-8cbb-96ff01c4df99.jpg)

Here is screenshot of tablet Samsung Galaxy details
![screenshot_2015-09-07-16-22-13](https://cloud.githubusercontent.com/assets/592627/9717736/cfa566ce-557d-11e5-8218-1838b1f1a258.jpg)

**Comment by agilecubeteam** [comment]
As  per our discussion we will not support this version. So, please close this bug.

**Comment by Aram4ik** [comment]
Client agreed that no need to support 4.0 version.
