### ISSUE TITLE
Dispatcher -clear reservation from queue

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#13]
Currently if taxi is available (is green) I can make him busy which removes him from queue. It's fine.
But if taxi has reservation (is red) I can't make him busy (remove from the queue). This is needed.
It would be better to rename the button to "Clear from the queue"

**Comment by agilecube** [comment]
Queue pop-up block should have functionality to "Clear from Queue" - On click of this button, the reservation/nearest zone reservation from all zones will be removed, and refresh the queue. 
- we shall estimate for approval

**Comment by agilecubeteam** [comment]
Question 1: clear will clear from all zones or particular zone?
Question 2: what will be status once cleared from zone?

**Comment by Aram4ik** [comment]
Current logic is like this:
1. show in a queue if available
2. show in a queue if busy and has reservation
3. don't show in a queue in other cases, ex if just busy

Currently reservation can be only in one zone so clearing his reservation and leaving him busy will remove him from queue
