### ISSUE TITLE
Dispatcher translations

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#14]
Please translate few buttons dispatcher always works with:

Block - Заблокировать
Make busy - Убрать с очереди
Close - Закрыть

**Comment by Aram4ik** [comment]
in open popup:

сделать первые - Сделать первым
Ясно из очереди - Снять из очереди

**Comment by Aram4ik** [comment]
Guys, it's getting really complicated to work with you cause I need to check absolutely every step, even copy-pasting words. Please test after you fix something..
![capture](https://cloud.githubusercontent.com/assets/592627/10607683/da6fe8ee-7743-11e5-8cc7-a41aadc19cf5.PNG)
![3](https://cloud.githubusercontent.com/assets/592627/10607684/da70b29c-7743-11e5-9406-84a30a9cdd95.PNG)

**Comment by agilecubeteam** [comment]
@Aram4ik 
Fixed means we have fixed.

They are not yet released. 

Once it is ready for your testing I will update you.

**Comment by Aram4ik** [comment]
Sorry. I saw you changed live one already - Ясно из очереди - Снять из очереди
And thought it's done everywhere
