### ISSUE TITLE
Dispatcher - make taxi first in a queue

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#17]
This is definitely enhancement. Please tell me the price.

When clicking on taxi driver (green on red) we see the popup. We need to add button Make first which changes his position in a queue to first

**Comment by agilecube** [comment]
ok, we shall estimate.

**Comment by Aram4ik** [comment]
Almost working. Button makes first but only after reserved taxies. So if I am 5th and first 2 positions are reserved (red) and other 2 are available (green) I will move to 3rd position

**Comment by Aram4ik** [comment]
In about 30 seconds after being pushed to the first position taxi driver is back to the last position

**Comment by agilecube** [comment]
@Aram4ik: Let me know if Mobile user can see his position update once the dispatcher make him first.

**Comment by agilecube** [comment]
Let it go, my team shall check what i asked.

**Comment by agilecube** [comment]
@agilecubeteam :  We checked on client's mobile. Here are  the scenario:
1) I was in "must", there was one taxi ahead with "reservation" status. dispatcher make me first. Success notification came, but my position in queue does not changed. 

2) I make my self available in "Priis". I was at 5th position, 3 ahead of me in available, and 1 ahead with reservation. So my queue shows on mobile - (3/1). dispatcher makes me first, Success notification came and i moved to first position in dispatcher Queue view. However, there is no affect on mobile queue. My position was still (3/1). I did manual refresh, nothing changed. 

3) The real one, we could not test : I am back to my old position in queue. I have a feel, when some one make an new entry to zone "Priis", then zone data refreshed, and positions are reloaded. Just an assumption, please check in detail.

Please check all three issues.

**Comment by agilecubeteam** [comment]
All above scenario tested now.
