### ISSUE TITLE
Dispatcher - change taxi status to reserved

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#18]
Here is such case. For example in zone number 5 are 20 taxi drivers and I am 7th. There are no one in zone number 6 for example and dispatcher receives an order there. Before (without system) they asked by radio - who want to take him and by radio they answered. In this case taxi driver does not lose his queue and even if queue in his zone number 5 goes on, he goes on up also. If next one is him but he is still doing that order he is first in queue but taxi driver gives order to second one until he receives to his zone.

What we need to do ( in our language :) )

Currently if taxi driver is busy he can reserve a zone. Dispatcher sees him red and does not give him order until he is green, even if he is first one. This is basically the same what we need BUT taxi driver can't make himself "reserved" if he is online. He can make reservation only from status busy and in this case he will lose his position in queue.

So what we thought - let's add a button to dispatcher's view in taxi popup - "Reservation". In Russian it is "Резервация". In this case dispatcher starts seeing him as red, in taxi view he sees that he is busy and sees his current zone as red. 

I hope you will understand what I wrote.

**Comment by agilecube** [comment]
Ok, we shall estimate.
