### ISSUE TITLE
Taxi - go live after reservation is impossible

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#19]
For example I started driving from zone 1 to zone 2. I reserved zone 2 cause I know I will be there soon. We have such condition that it's possible to go live only if you are currently in same zone you reserved.

BUT.. it does not work. I had a reservation in LINN and have been in LINN. After clicking go live I've received message that I can go live only from same zone where is my current reservation. Please check

**Comment by agilecubeteam** [comment]
we have tested this issue and it's work properly , so we can not re produce.

**Comment by Aram4ik** [comment]
I will try tomorrow once again

**Comment by Aram4ik** [comment]
Just skip it currently
