### ISSUE TITLE
Blank screen Android 4.1

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#2]
just blank screen after launching app

**Comment by Aram4ik** [comment]
Similar to just blank issue. This happened on Android 4.4 after changing status from busy to available
![a5c740bce60de937f97834f9ad22d65e0e3e1e51da7ac723b41089a3305121e1](https://cloud.githubusercontent.com/assets/592627/9838439/6ed9ff92-5a66-11e5-9030-b3ed01ff7791.jpg)

**Comment by agilecubeteam** [comment]
just try to scroll down, because of previous long list of all zone and switch to only nearest zone screen is showing blank.
if you scroll down once it will show correct list.
