### ISSUE TITLE
Taxi Positioning / GPS

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#21]
Most urgent. TOP priority. This is already for few months and never been solved for 100%

![d833e63d6ba81ef68d2b34bb4b0c9d2b6570c97ed59f412df8aec53523e03dc4](https://cloud.githubusercontent.com/assets/592627/10376825/b5308f1e-6e08-11e5-8b85-73670f5354b0.jpg)

**Comment by agilecube** [comment]
please provide android version.

**Comment by agilecube** [comment]
Let's give manual refresh button. Please provide location and text.

**Comment by Aram4ik** [comment]
Also taping on zone name will send current geolocation (not only icon)
![d833e63d6ba81ef68d2b34bb4b0c9d2b6570c97ed59f412df8aec53523e03dc4](https://cloud.githubusercontent.com/assets/592627/10393733/244d011a-6e9b-11e5-8da8-f473aa7308c3.jpg)

**Comment by Aram4ik** [comment]
Still not working properly always. Sometimes is wrong positioning. Refresh does not help. Please attach here a file with function which is responsible. I will try to find a bug place. Thank you.

**Comment by Aram4ik** [comment]
Once again - Still not working properly always. Sometimes is wrong positioning. Refresh does not help. Please attach here a file with function which is responsible. I will try to find a bug place. Thank you.

Another thing - in 1 minute 3 times zone changed itself from A to B then to A then to B etc..
Amigo people already think about switching off the GPS positioning cause this issue cannot be solved for several months..

**Comment by agilecube** [comment]
@Aram4ik : As we have not been able to reproduce issue with your mobile, just now. Let me other way to test.

**Comment by agilecube** [comment]
@Aram4ik: As per our discussion now, client will test one more time, and it happen again they will give they give device.

**Comment by Aram4ik** [comment]
Correct

**Comment by Aram4ik** [comment]
Does not work. See the video below
https://www.youtube.com/watch?v=Wlk8Qs-J6B8

Sony Xperia Z3 / Android 5.1.1.
