### ISSUE TITLE
Taxi - iOS header buttons

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#22]
![dsc_8237](https://cloud.githubusercontent.com/assets/592627/10376881/fe0cb6ae-6e08-11e5-9794-bccde7de60aa.JPG)

**Comment by agilecube** [comment]
let's give screenshot for ios and android both without custom css

**Comment by agilecubeteam** [comment]
![without custome css in ios simulator screen shot oct 12 2015 12 19 53 am](https://cloud.githubusercontent.com/assets/14108944/10423361/ad826fb6-707a-11e5-98aa-23bb3b351050.png)

**Comment by agilecubeteam** [comment]
![without custome css in android screen shot 2015-10-12 at 12 43 05 am](https://cloud.githubusercontent.com/assets/14108944/10423371/be96ba28-707a-11e5-8516-f138a0c21327.png)

**Comment by agilecubeteam** [comment]
please check 2 screenshots of android and ios (without custom css).

**Comment by Aram4ik** [comment]
Looks fine. We need buttons bigger now

**Comment by agilecubeteam** [comment]
it's covered in #25, so marking as duplicate
