### ISSUE TITLE
Taxi - design issues

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#25]
Please make header buttons square by increasing the height almost twice. They still miss while tapping.
Please make zone titles bigger by decreasing upper and bottom padding

**Comment by agilecube** [comment]
Header should be square, and button should be square too. not sure how it will work on iOS. we shall give you screen shot of iOS and android.

**Comment by Aram4ik** [comment]
![d833e63d6ba81ef68d2b34bb4b0c9d2b6570c97ed59f412df8aec53523e03dc4](https://cloud.githubusercontent.com/assets/592627/10393959/9c56d5b8-6e9c-11e5-8f16-94b035cf1877.jpg)

**Comment by agilecubeteam** [comment]
![ios simulator screen shot oct 12 2015 3 51 43 am](https://cloud.githubusercontent.com/assets/14108944/10426387/b6805f14-7094-11e5-892c-ee47132b8b48.png)

please approve this screen shot (changes in header bar)

**Comment by Aram4ik** [comment]
It's fine but I don't get why we need the place in yellow area. Let's remove it
![b6805f14-7094-11e5-892c-ee47132b8b48](https://cloud.githubusercontent.com/assets/592627/10434612/4acd829e-7123-11e5-94a9-015ea5f74043.png)

**Comment by agilecube** [comment]
@Aram4ik : that' simulator information inbuilt, the one you see on all app on top - like how much battery, what is signal strength. Let me know your concern.

**Comment by Aram4ik** [comment]
Aah, okaay :) then it's fine
