### ISSUE TITLE
Taxi - zones update while driving

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#26]
Please check in what interval of sending geolocation to database. All taxi drivers complain that it takes about 500 meters (which is too much) or ~1 minute to update the zone I entered.
Amigo guys asked maybe it's better to add Update button which will send immediately geolocation to DB. All taxi drivers know zone borders perfectly.

**Comment by agilecube** [comment]
refresh button , which is covered in issue #21

**Comment by Aram4ik** [comment]
Now is fine but wrong numbers are shown. Let's imagine such situation:
1. Available
2. Reservation
3. Available
4. Me
5. Reservation
6. Available

I should see 2 numbers - 2 and 1 which means that 2 are available and 1 is busy before me. I see currently 2 and 2 which mean that the number shows correct number of available taxies before me and ALL taxies in reservation.
I need to see reservations count before me ONLY.
Thank you

**Comment by agilecubeteam** [comment]
@Aram4ik 
As per initial logic 

If I am "Available" I can see count which is above me with "Available" status & Total Reservation
If I am "Reservation" I can see count which is above me with "Reservation" status & Total Available

Let me know if you need to change logic as you are suggesting now. Also let us know what should be count in case of Reservation status

**Comment by Aram4ik** [comment]
Hm. Those numbers are made to know how many people are before you to calculate approximate time before your order. With this logic it's impossible.
In both ways we need to know how many are available before me and how many are "reservation" before me. By putting those numbers together I can define my position in a queue.

**Comment by agilecubeteam** [comment]
@Aram4ik 
I understand, 
Logic should be as per client's need. This was just for your information.
We will change code as per your comment.

In zone where I am available / Reservation, it should show count of taxis above me for both "Available" and "Reservation".

**Comment by Aram4ik** [comment]
Correct
