### ISSUE TITLE
Taxi - moving from nozone to zone

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#29]
If taxi driver quits all zones and then drives back he appears online only after crossing first zone to second. Attaching image.
![323](https://cloud.githubusercontent.com/assets/592627/10378939/8e409c3a-6e14-11e5-8164-84e2e3d53a86.png)

Here you see 2 examples. First is taxi enters to zone number 1 then 2. Only in zone 2 app finds him and shows that he is in zone number 2. In zone number 1 shows he searches zones.

Same happens when he enters zone number 7 and then number 6. In 6 is detection in 7 searches.

**Comment by agilecube** [comment]
Let's just have refresh button. Same as issue#21
