### ISSUE TITLE
Zone detection Android 4.4.2 Samsung Galaxy tab

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#3]
Issue with zone detection - continuous searching. Google maps detects right location in ~ 10 sec (little bit longer than usual)

**Comment by Aram4ik** [comment]
Still does not work properly..

**Comment by agilecubeteam** [comment]
Let us know what is the problem, see attached results on emulator. 

![screen shot 2015-09-22 at 2 26 54 am](https://cloud.githubusercontent.com/assets/14108944/10015309/1d16b276-613d-11e5-9a46-485d26fd9ef9.png)
![screen shot 2015-09-22 at 2 26 12 am](https://cloud.githubusercontent.com/assets/14108944/10015310/1d1a06d8-613d-11e5-8349-1f7cad2923e7.png)
