### ISSUE TITLE
Nearest zone clears itself

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#31]
After adding myself to nearest zone it disappears in 5 minutes (sometime). Happens in all devices

**Comment by agilecubeteam** [comment]
@Aram4ik 
IOS 9, we are not supporting as of now.

**Comment by agilecube** [comment]
@Aram: Please let us know steps. This is only possible if Dispatcher making him busy from back-office for testing purpose.

**Comment by agilecube** [comment]
@agilecubeteam : Please check one time, client is not hearing from user, but just check ones.

**Comment by agilecubeteam** [comment]
Tested for duration of about 1 hour, could not able to reproduce this.
