### ISSUE TITLE
Stuck in zone 

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#38]
As talked in skype:
Please attach the js part where we ask for current zone by sending our location. 

Issue itself: randomly and quite seldom zone refresh stops updating. Manual refresh refreshes the queue. After exit and new log in it works again

**Comment by Aram4ik** [comment]
Try to reproduce like this:
1. be available in some zone / reserve some zone
2. receive a phone call and talk for 1 min
3. drop a call and see what happens

**Comment by agilecube** [comment]
@Aram4ik : We tried above steps, could not able to reproduce. All position in Queue maintained, and zone also got updated after call dropped.

**Comment by agilecube** [comment]
Nearest zone issue - I am currently in zone 1 and reserved myself to nearest zone number 2. In example I want to go to gas station and occasionally move to zone number 3. This should happen - If zone number 2 is the nearest zone of number 3 then everything is fine - so I am in zone number 3 and my previous reservation to zone 2 does not change. But if zone number 2 is not the nearest zone of number 3, then the nearest zone is automatically the zone where I came from, in this case zone number 1.

----- Above logic must be creating problem when user drives on zone borders.

**Comment by Aram4ik** [comment]
Nope. We don't talk about such case.
We have 2 cases:
1. I am available and I'm not moving. I see myself going up in the queue and suddenly I'm the last one
2. I am in reservation in one zone and locating in another zone. It does not matter where am I, moving or not, my reservation position goes up. I arrive to this zone and click a button to go live and it drops me to the bottom of the queue. This should not happen. My queue position should not change. Only status.

**Comment by agilecube** [comment]
Here is documentation of requirement given to us - word-to-word.

**Comment by agilecube** [comment]
![root-cause-functionality](https://cloud.githubusercontent.com/assets/13015900/11177691/569c9d98-8c6d-11e5-9e4a-1ae8d534314e.png)

**Comment by agilecube** [comment]
As per discussion, will have separate Package to observe the behavior and Logger.  - #43 , #44
