### ISSUE TITLE
Taxi queue issue

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#39]
I have seen with my eyes that a user was second in a queue and then someone appeared in front of him

**Comment by Aram4ik** [comment]
Try to reproduce like this:
1. be available in some zone / reserve some zone
2. receive a phone call and talk for 1 min
3. drop a call and see what happens

**Comment by agilecube** [comment]
@Aram4ik : We tried above steps, could not able to reproduce. All position in Queue maintained, and zone also got updated after call dropped.

**Comment by agilecube** [comment]
1. Nearest zone issue - I am currently in zone 1 and reserved myself to nearest zone number 2. In example I want to go to gas station and occasionally move to zone number 3. This should happen - If zone number 2 is the nearest zone of number 3 then everything is fine - so I am in zone number 3 and my previous reservation to zone 2 does not change. But if zone number 2 is not the nearest zone of number 3, then the nearest zone is automatically the zone where I came from, in this case zone number 1.

----- Above logic must be creating problem when user drives on zone borders.

**Comment by Aram4ik** [comment]
Commented in #38

**Comment by agilecube** [comment]
Commented in #38

**Comment by agilecube** [comment]
As per discussion, will have separate Package to observe the behavior and Logger.  - #43 , #44
