### ISSUE TITLE
Changing password for taxi

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#4]
Password does not changes from admin side for taxi driver

**Comment by agilecubeteam** [comment]
Minimum 6 char password is required. We changed password to 123456 for taxi 109 and it worked. 

Looks like validation pop-up did not worked on your browser. Please let us know on which browser client is testing !!

**Comment by Aram4ik** [comment]
It works!

**Comment by Aram4ik** [comment]
Can't change password for user 32. Please check
Screenshot http://pasteboard.co/xrionqG.png

**Comment by Aram4ik** [comment]
Amigo guys needed 32nd as soon as possible and I deleted him and created again. You have a little log there. Can you please check using it what was wrong? Thank you
