### ISSUE TITLE
GPS Support remove 

### ISSUE THREAD

**Issue by agilecube** [agilecube/Amigo#41]
We need a version which does not have GPS location detection
## Change in app:
- After Login , instead "detecting zone" Give message "Select current zone"
- User has to go to "All zone" and tap and hold to select current zone
- rest all functionality will be same.
- remove recurring service call of giving GPS location to back end.

**Comment by Aram4ik** [comment]
1. after login my current zone is NULL
2. While LIVE selecting zone from ALL tab will change my current zone. If I have nearest zone reservation and it is not the nearest zone of new selected zone - nearst zone is cleared.
3. While LIVE selecting zone from NEAR tab will change my nearest zone
4. While BUSY/changing to BUSY my current zone is NULL
5. While BUSY, after reservation everything is same
6. While BUSY and having reservation, going LIVE app changes current zone to reservation zone and goes LIVE

**Comment by Aram4ik** [comment]
Select current zone = Выберите зону

**Comment by agilecubeteam** [comment]
@Aram4ik 
One of the side effect of this change is on Map.
After this change we are not going to have Lat, Long for taxi and hence not possible to show them on MAP.
Please confirm.

**Comment by Aram4ik** [comment]
Confirming. Talked about that with client yesterday

**Comment by agilecube** [comment]
okey
