### ISSUE TITLE
Current zone is not active

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#47]
I don't know exact steps but logic is like this:
- user takes an order and goes to Busy
- after he comes back he sees himself green
- he reserves a nearest zone and sees green as current and yellow as nearest

Everything seems correct but dispatcher does not see him in his current zone which means he is not registered there.
And of course user realizes this after he wait for some time, makes manual refresh and sees that instead of moving forward in a queue he moves back (which is logical cause he has not reserved anything).

Possible solution for this should be control while reserving nearest zone:
nearestZone.click() {
   if(currentZone == null) {
      makeGreenZoneAsCurrentZone();
   }
   reserveNearestZone();
}

**Comment by agilecube** [comment]
umm.. Aram my team is not able to reproduce this. Let's talk when you are available to understand more.
