### ISSUE TITLE
Blocking taxi driver

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#5]
If dispatcher blocks taxi driver taxi driver should be removed from the queue. This one works.
But then taxi driver can immediately add himself to queue again. This one should not happen until dispatcher removes block from taxi driver.

**Comment by agilecubeteam** [comment]
So you want to give some message? If yes, please provide message.

**Comment by Aram4ik** [comment]
No. The point is to block taxi drives that he can't work (add himself to queue) until he's unblocked. Currently it works for a second

**Comment by agilecubeteam** [comment]
Taxi driver can do it by clicking on it. So, do you want to restrict click? or restrict click with some message?

**Comment by Aram4ik** [comment]
Currently we talk about dispatcher view. After clicking on taxi number dispatcher can block taxi. But it does not block but just clears himself from the queue. After blocking taxi driver should not be able to add himself to queue again.
![333](https://cloud.githubusercontent.com/assets/592627/9848496/5bad56d8-5aea-11e5-8919-d9eefb9a9595.JPG)

**Comment by agilecubeteam** [comment]
okey. got solution
