### ISSUE TITLE
Reservation time

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#7]
Reservation for taxi driver while busy should not be longer than one hour. We talked about this before. If's not critical, but if possible, please do it and tell me how much it will cost. Also possible to move it to phase to.

Logic could be easy - simple cron which controls all reservation every 5 minutes and compares with current time. I can write it if you are too busy. Thank you

**Comment by agilecubeteam** [comment]
I still insist to move it to Phase-2.  As i feel that what if taxi driver reserve it, and somehow he took more than an hour to reach to the target zone. Also, i am sure there will be some more consequences. 

I would like to let the current functionality go stable and then move on to new enhancement.

**Comment by Aram4ik** [comment]
From one end of the Tallinn to second is max 30 minutes. It's the longest way but usually it does not take longer than 10-12 minutes. And of course, all taxi drivers will know that you cannot reserve a place in a queue for longer than 60 minutes. We will not definitely do anything besides just dropping them from the queue. Current problem is that they reserved something and just stay in a queue and disturb dispatcher to work properly. So we need to make next steps:
1. Select to database all active reservations. It's the same as what dispatcher sees, but just with filtering the type of reservation. I mean you should have very similar request to database.
2. foreach the result
3. compare 2 dates. If difference longer than 60 minutes call same function as taxi calls to clear reservation

That's it.
