### ISSUE TITLE
CSS fixes

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#8]
/\* queue numbers bigger */
# queue .zone ul li {

```
font-weight: bold;
font-size: 21px;
color: #fff;
```

}

/\* reservation background darker */
.btn-dan {
    background-color: #CE2B33 !important;
}

/\* available reservation background darker */
.btn-available {
    background-color: #0EB547 !important;
}

/\* queue background little bit more grey */
.page-container-bg-solid .page-content {
    background: #E4E5E6;
}

**Comment by agilecubeteam** [comment]
All CSS changes for Mobile or anything for Web also ?

**Comment by agilecubeteam** [comment]
Looks like all for Web. Please let me know if wrong.

**Comment by Aram4ik** [comment]
Yep. It's for dispatcher

**Comment by Aram4ik** [comment]
Works. Thank you
