### ISSUE TITLE
Android 4.1 visual difference from others

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#9]
4.1 is on the right.
Header and buttons are smaller, zones are not bold and queue values are also small in smaller boxes
![074f39fae9d1ed567bb51b3c64071ac57e9a695519c25a50ece6de8e509d7c0f](https://cloud.githubusercontent.com/assets/592627/9838428/18dcce12-5a66-11e5-9b9d-caa98dd0c87a.jpg)

**Comment by agilecubeteam** [comment]
This is in contradiction with issue #2. Please let us know which issue need to be checked.

**Comment by Aram4ik** [comment]
mm. I guess both. I just had a phone call and they told again about wrong positioning (positioning in different zone)

**Comment by Aram4ik** [comment]
PS. not on all 4.1 devices is blank screen. It happens sometimes

**Comment by Aram4ik** [comment]
You can copy current version to web and I will send you a css fix.

**Comment by agilecubeteam** [comment]
we have uploaded web version

**Comment by Aram4ik** [comment]
don't have currently 4.1 device.. you can upload such version to play market

**Comment by agilecubeteam** [comment]
@Aram4ik 
We tried with inline style and it worked. Let's my team do it for all screen and will release.
Note: inline style may not allowed in iphone. so, we have to create two different set of code.
